// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolicyService.Infrastructure.Persistence;

#nullable disable

namespace PolicyService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260922114951_AddPolicyTypeAvailability")]
    partial class AddPolicyTypeAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolicyService.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PolicyTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PremiumFrequency")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PremiumPlanId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("PolicyTypeId");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("PolicyService.Domain.Entities.PolicyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PolicyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fba5c78-2de5-4857-9e29-0a091572a001"),
                            BasePremium = 12500m,
                            Code = "HEALTH_STANDARD",
                            Description = "Standard individual health policy.",
                            IsAvailable = true,
                            Name = "Health Standard"
                        },
                        new
                        {
                            Id = new Guid("4fba5c78-2de5-4857-9e29-0a091572a002"),
                            BasePremium = 9300m,
                            Code = "AUTO_COMPREHENSIVE",
                            Description = "Comprehensive motor insurance coverage.",
                            IsAvailable = true,
                            Name = "Auto Comprehensive"
                        },
                        new
                        {
                            Id = new Guid("4fba5c78-2de5-4857-9e29-0a091572a003"),
                            BasePremium = 15000m,
                            Code = "LIFE_PROTECT",
                            Description = "Long-term life protection policy.",
                            IsAvailable = true,
                            Name = "Life Protect"
                        });
                });

            modelBuilder.Entity("PolicyService.Domain.Entities.Policy", b =>
                {
                    b.HasOne("PolicyService.Domain.Entities.PolicyType", "PolicyType")
                        .WithMany()
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("PolicyService.Domain.Entities.Coverage", "Coverages", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Deductible")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("SumInsured")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("PolicyId");

                            b1.ToTable("PolicyCoverages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");
                        });

                    b.OwnsMany("PolicyService.Domain.Entities.PolicyHistory", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTime>("ChangedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Remarks")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PolicyId");

                            b1.ToTable("PolicyHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");
                        });

                    b.Navigation("Coverages");

                    b.Navigation("History");

                    b.Navigation("PolicyType");
                });
#pragma warning restore 612, 618
        }
    }
}
